#!/usr/bin/env sh

#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# More indepth commands
# - https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#window

# Some of the configs also came from Jesse Skelton
# https://www.notion.so/Yabai-8da3b829872d432fac43181b7ff628fc
#

# ** LAYOUT **
yabai -m config layout                       bsp
yabai -m config window_placement             second_child

# ** PADDING **
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   2

# ** SPLIT RATIOS **
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.5

# ** MOUSE SUPPORT **
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config mouse_drop_action            swap

# ** Window Modifications **
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_opacity_duration      0.0

# ** Window Boarder **
yabai -m config window_border                on
yabai -m config window_border_width          3
# Dark Purple 0xFF8B008B
# Olive       0xFF6B8E23
yabai -m config active_window_border_color   0xFF6B8E23
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

yabai -m config debug_output on

# My custom space names for my 3 monitor setup. These names are used in some of my scripts.
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three --layout float
yabai -m space 4 --label four
yabai -m space 5 --label five
#yabai -m space 6 --label six
#yabai -m space 9 --label nine

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Finder" layer=above manage=off

yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^TeamViewer$" sticky=off layer=above manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
#yabai -m rule --add app="^Photos$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="iStat Menus.*" manage=off mouse_follows_focus=off
yabai -m rule --add title="JetBrains Toolbox" manage=off mouse_follows_focus=off
yabai -m rule --add title="App Store" manage=off mouse_follows_focus=off
yabai -m rule --add title="^Parallels$" manage=off
#yabai -m rule --add app="^CLion$" manage=off
yabai -m rule --add app="^PyCharm$" manage=off
yabai -m rule --add app="IntelliJ IDEA" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off


# Name of the intelij project use the query to see what name is
#yabai -m rule --add app="Main" space=6
#yabai -m query --windows --space 3



echo "yabai configuration loaded.."
